---
- hosts: 172.31.88.57
  become: yes
  tasks: 
  - name: template practice
    template:
     src: myindex.j2
     dest: /var/www/html/index.html
  - name: Get_url
    get_url:
     url: https://maha22aug22.s3.us-east-2.amazonaws.com/mahaLogin.war
     dest: ?home/ubuntu/mahaLogin.war
    force_basic_auth: yes
