---
- hosts: 172.31.88.57
  become: yes
  tasks: 
  - name: template practice
    template:
     src: myindex.j2
     dest: /var/www/html/index.html

  - name: ggggig
    get_url:
     url: https://aeroplane987.s3.amazonaws.com/ubuntu2.txt
     dest: /home/ubuntu/ubuntu2.txt
     force_basic_auth: yes
