---
- hosts: 172.31.88.57
  become: yes
  tasks: 
  - name: template practice
    template:
     src: myindex.j2
     dest: /var/www/html/index.html

  - name: ggggig
    get_url:
     url: https://chat.openai.com/c/79ef25bf-4949-4ccd-a6dc-10afffcb8920
     dest: home/ubuntu/mahaLogin.war
     force_basic_auth: yes
