---
- hosts: 172.31.88.57
  become: yes
  tasks: 
  - name: template practice
    template:
     src: myindex.j2
     dest: /var/www/html/index.html
    notify: to restart the service

  handlers: 
    - name: to restart the service
      service:
        name: apache2
        state: restarted
