---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install webserver on RedHat 
    yum:
     name: "{{javapackonredhat}}"
     state: present
    when: ansible_os_family =="RedHat"
  -  name: webserver on ubuntu
     apt:
      name: "{{webpackonubuntu}}"
      state: present
     when: ansible_os_family =="Debian"
  -  name: webserver on ubuntu
     apt:
      name: "{{Npackonubuntu}}"
      state: present
     when: ansible_os_family =="Debian" 
  - name: install git
    apt:
      name: git
      state: present
    tags: mygit     
     

   

    

 
    


  
    

  
    