---
- hosts: all
  become: yes
  tasks:
  - name: i want to inatll tree
    apt: 
     name: tree
     state: present
  - name: i want install apache2
    apt:
     name: apache2
     state: present
  - name: Install the version '1.18.0' of package "nginx" and allow potential downgrades
    ansible.builtin.apt:
     name: nginx=1.18.0
     state: present
     allow_downgrade: yes  