---
- hosts: 172.31.88.57
  become: yes
  tasks:
    - include_tasks: myfile.yml
    - name: copy files
      copy:
       src: kohli2.txt
       dest: /home/ubuntu/my2ndfile

    - name: copy files
      copyy:
       src: kohli2.txt
       dest: /home/ubuntu/my2ndfile
      ignore_errors: yes 
       