---
- hosts: 172.31.88.57
  become: yes
  tasks:
    
    - name: copy files
      copy:
       srcc: kohli2.txt
       dest: /home/ubuntu/my2ndfile
      ignore_errors: yes 

    - name: copy files
      copy:
       src: kohli2.txt
       dest: /home/ubuntu/my2dfile
     
       